### ISSUE TITLE
Configuration of Sound Canvas VA can't be applied

### ISSUE THREAD

**Issue by zhangboyang** [kode54/foo_midi#14]
![foo_midi_scva](https://cloud.githubusercontent.com/assets/7912829/14396001/becd37fe-fe07-11e5-967a-06d5255dc212.png)

**How to reproduce:**
First, open the "Configure" window of SCVA, and set the volume to minimal.
Then play a midi file, the sound should be muted but the sound still exists.

**Comment by zhangboyang** [comment]
The configuration is saved, but it won't apply to the playback. Because when I closed foobar2000 and reopen it, the volume configuration is minimal (as I configured before).

**Comment by kode54** [comment]
This VST instrument does not seem to remember any settings applied to it programmatically, it seems to ignore that I am applying settings to it on startup and overrides them with the defaults once playback actually starts. I am doing nothing different from saving or restoring settings from any other VST instrument, so obviously this component does not restore its state properly.

I have also observed that it takes actually opening the dialog and clicking the Reset button to make the preset apply to a new instance of the actual SCVA core.

I may just bypass the VST and use the SCVA core, but then I'd have to implement all the controls myself, as well as the reset behavior and message filtering. Nope.

**Comment by zhangboyang** [comment]
I think I figure out the problem.
I added some logging code to 'vsthost/vsthost.cpp', like this:
![vsthostcpp](https://cloud.githubusercontent.com/assets/7912829/14405651/25f165e0-fec6-11e5-8a66-cce4436018d3.PNG)
Then running foobar2000 outputs this:
![log](https://cloud.githubusercontent.com/assets/7912829/14405665/68499430-fec6-11e5-84e0-cfcd42dba28e.PNG)
I found that the host is terminated and restarted after sending configuration (code 2).

I read some code in 'midi.cpp', and I found that the host process is terminated immediately after setting sample rate:
![midi](https://cloud.githubusercontent.com/assets/7912829/14405725/76270c62-fec7-11e5-942c-633ccf28f95b.PNG)

The setChunk() should copy configuration data to blChunk, so the startup() will use it to initialize VST, but the code didn't do that, the first line seems wrong. Finally, I changed setChunk() to this:
![patch](https://cloud.githubusercontent.com/assets/7912829/14405783/40f51c04-fec8-11e5-9180-6eb18501565c.PNG)

Now the volume can be remembered.

**Comment by zhangboyang** [comment]
However, there seems to be a bug in SCVA ver1.0.2 that it can't automaticly send "Map Mode" to its core unless I manually click the 'RESET' button. So I have to add a call of displayEditorModal() to startup(), and manually click the 'RESET' button in order to set "Map Mode" to "SC-88". Ahhhhhhhhhh

**Comment by kode54** [comment]
The bug with having to click Reset is completely random with the new version I just committed and uploaded. It will also randomly display a parameter 1 such error when that is likely to happen, then it will seem to play mostly pianos.

**Comment by zhangboyang** [comment]
OK, the bug is fixed, thank you.
:)
