### ISSUE TITLE
vsthost might crash when (sample rate % 1000 != 0)

### ISSUE THREAD

**Issue by zhangboyang** [kode54/foo_midi#15]
How to reproduce:

I'm using SCVA as my VSTi, and I found the vsthost randomly crashes when playing MID files.
This only happens when sample rate is not a multiple of 1000, like 44100, 88200, etc.
If I change the sample rate to multiples of 1000, like 48000, the vsthost no longer crashes.

**Comment by zhangboyang** [comment]
Changing these 2 places of 'vsthost/vsthost.cpp' seems to fix the crash.
first:
![1](https://cloud.githubusercontent.com/assets/7912829/14405875/733b08ce-fecb-11e5-815e-b9eea53cf5ff.PNG)
second:
![2](https://cloud.githubusercontent.com/assets/7912829/14405876/733e556a-fecb-11e5-8875-5853e70938e5.PNG)

But I'm not sure if there are any side efforts of these two changes......

**Comment by kode54** [comment]
This has been reverted back to the original method of buffering _up to_ 4096 samples at a time, and rendering less than that if MIDI events occur more frequently, as may tend to happen. Version 1.0.1.0 or possibly 1.0.2.0 of Sound Canvas VA fixes this issue, but introduces others that are even more annoying.

**Comment by zhangboyang** [comment]
OK, the bug is fixed, thank you.
:)
