### ISSUE TITLE
sfz support

### ISSUE THREAD

**Issue by przemoc** [kode54/foo_midi#9]
According to [BASS_MIDI and SFZ files](http://www.un4seen.com/forum/?topic=12405) topic on Un4seen Dev Forum there is a BASSMIDI version supporting sfz format. I'm not sure how complete it is, though. Anyway, it would be really nice to have (even partial) sfz support in foobar2000.

---

Just for the record, more about sfz can be found in a few places like:

- [Cakewalk DevXchange - Specifications - sfz File Format](http://betaforum.cakewalk.com/DevXchange/article.aspx?aid=108) - official sfz 1.0 specification
- [Cakewalk DevXchange - Specifications - sfz Samples](http://betaforum.cakewalk.com/DevXchange/article.aspx?aid=118) - example .sfz definition files showing every opcode functionality
- [Cakewalk Synthesizers: from Presets to Power User](http://noisesculpture.com/cakewalk-synthesizers) book by Simon Cann - chapter 13 and appendix - official sfz 2.0 specification (apparently unavailable online)
- [The sfz format](http://www.sfzformat.com/) - reformatted copy of sfz 1.0 specification, maintained by Chad Beckwith (from PatchArena)
- [sfz format](http://drealm.info/sfz/plj-sfz.xhtml) - an alternative view of the sfz format documentation by Peter L Jones

**Comment by przemoc** [comment]
Ok, I finally rechecked things today. You've updated foo_midi and BASSMIDI-Driver, so they use newer BASS libraries (https://github.com/kode54/foo_midi/commit/a070b59a707cf5b8e7121aec3c244d9e26274b55, https://github.com/kode54/BASSMIDI-Driver/commit/7641c21e874b45ce850f7d491304f7c5cba0fa8e) and BASSMIDI-Driver supports bank,patch mapping syntax (https://github.com/kode54/BASSMIDI-Driver/commit/a994f38b4bd7ca3915ecee40f7b38df383d73b52). I uninstalled old versions and installed the recent ones.

I used VMPK to test wav-based `Piano-Steinway.sfz` (mentioned in https://github.com/kode54/foo_midi/issues/9/#issuecomment-62325017), ogg-based `Multi Pluck.sfz` (mentioned in https://github.com/kode54/foo_midi/issues/9/#issuecomment-62489455) and another wav-based `Detuned Saws.sfz` (mentioned in https://github.com/kode54/foo_midi/issues/9/#issuecomment-62540807) by providing proper `.sflist` files (with `p0,0=0,0|X:\path\to\file.sfz` as their sole content) in "Configure BASSMIDI Driver". All of them seem to work fine. Yay! :)

So I switched to foobar2000 and tried to play `moonlight1.mid` (mentioned in https://github.com/kode54/foo_midi/issues/9/#issuecomment-62489455) with each of above mentioned SFZ files (using same `.sflist` files I used for BASSMIDI Driver). No luck! I cannot hear MIDI file played in foobar2000 with foo_midi 1.239 using those SFZ files, even when instrument and bank changes are disabled. Boo! :(

I use Windows 7 x64, but I verified that almost all BASS libraries (exceptions are `bassopus.dll` and `basswv.dll`, but they don't matter in this issue) shipped with 32-bit part of BASSMIDI Driver are the same as the ones used in foo_midi. So it seems that there is supposedly some mistake in non-BASS part of foo_midi, i.e. `foo_midi.dll` itself. Just to be sure that `.sflist` files with bank,patch mapping work at all in foo_midi I tried `.sflist` file with SF2 instrument (`p0,0=0,0|X:\path\to\file.sf2`) and at least that worked (which hopefully narrow code paths involved in the bug).

If there is any way I could help you in tracking down the problem, then please tell. If you haven't done so yet, then I think that trying to play MIDI yourself with `.sflist`s using those SFZ files (at least `Multi Pluck.sfz` and `Detuned Saws.sfz`, as they are easily accessible) via BASSMIDI Driver and foobar2000+foo_midi with some debugging turned on should allow you to pinpoint the issue far easier (and likely faster too).

**Comment by kode54** [comment]
Check if this is fixed with the latest update.

**Comment by przemoc** [comment]
Yes, foo_midi 1.241 seem to be working with SFZ finally! Thank you, @kode54!
